### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by matks** [BudzynskiMaciej/Personal-Blog-Source#1]
Without a license, the default copyright laws apply to your Hugo theme, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Source https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

I wish to reuse your Hugo theme but I dont know if I can because there is no license 😉

**Comment by BudzynskiMaciej** [comment]
Feel free to take it, I will provide a MIT license in nearby future. 😄 

![image](https://user-images.githubusercontent.com/19284904/143878565-34d2e599-a9f7-42a3-b2cf-30641a98096b.png)

**Comment by matks** [comment]
Thank you for answer, I then close the issue as it's resolved
